import { Inter } from 'next/font/google'
import './globals.css'

import { Metadata } from 'next'
import type { ReactNode } from 'react'
import FooterWrapper from './components/FooterWrapper'
import NavbarWrapper from './components/NarbarWrapper'
import { AppProvider } from './providers/NextUiProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<AppProvider>
					<NavbarWrapper />
					{children}
					<FooterWrapper />
				</AppProvider>
			</body>
		</html>
	)
}
