import { Inter } from 'next/font/google'
import './globals.css'

import { cn } from '@nextui-org/react'
import { Metadata } from 'next'
import Layout from './components/Layout'
import { AppProvider } from './providers/NextUiProvider'
import { PageProvider } from './providers/PageProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={cn('dark', inter.className)}>
			<body>
				<AppProvider>
					<PageProvider>
						<Layout>{children}</Layout>
					</PageProvider>
				</AppProvider>
			</body>
		</html>
	)
}
